import { compile } from '../../dist/main.js';

export default function plugin(options = {}) {
  const {
    runtimePath = '10x/runtime',
    atomicCss = true,
    hmr = true,
    include,
    exclude,
    ...compileOptions
  } = options;

  const includePattern = include || /\.md(?:$|\?)/;
  const excludePattern = exclude || null;

  const shouldTransform = (id, code) => {
    if (!includePattern.test(id)) return false;
    if (excludePattern && excludePattern.test(id)) return false;
    // Skip if already compiled
    if (code.includes('// Generated by 10x compiler')) return false;
    return true;
  };

  return {
    name: 'vite-plugin-10x',
    enforce: 'pre',
    transform(code, id) {
      if (!shouldTransform(id, code)) return null;
      return {
        code: compile(code, {
          runtimePath,
          atomicCss,
          hmr,
          ...compileOptions,
        }),
        map: null,
      };
    },
  };
}
